name: 'Deploy'
on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        required: false
        default: '~1.1.9'
      workspaces:
        type: string
        required: true
      working_dir:
        type: string
        required: true
    secrets:
      TF_API_TOKEN:
        required: true
      GH_SSH_PRIVATE_KEY:
        required: true
jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        terraform_version:
          - ${{ inputs.terraform_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ matrix.terraform_version }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -recursive -check
      working-directory: ${{ inputs.working_dir }}

  validate:
    name: Validate
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        terraform_version:
          - ${{ inputs.terraform_version }}
        workspaces: 
          - ${{ inputs.workspaces }}
    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ matrix.terraform_version }}
        cli_config_credentials_hostname: app.terraform.io
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform init
      id: init
      run: terraform init
      working-directory: ./${{ matrix.workspaces }}
      env:
        GIT_SSH_COMMAND: "echo '${{ secrets.GH_SSH_PRIVATE_KEY }}' > id_rsa
          && ssh-keyscan github.com > known_hosts
          && chmod 600 id_rsa known_hosts
          && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./${{ matrix.workspaces }}
